### PR TITLE
[FEATURE] #1: update paypal express module for hyva to work with late…

### PR DESCRIPTION
**Pull request by mautz-et-tong**
…st stable checkout version

- add translation files for various languages

- add license file

- add credits and license to readme file

### CODE REVIEW

**Comment by wigman** [comment]
Hi Irene, I'm sorry, that PR went completely under my radar. I've merged it and tagged an 1.0.1 release.

Please note that I've also renamed the repo to hyva-themes/magento2-react-checkout-paypal-express.

I've made the repo public and I'll ask people to start testing it now :)

Thanks a lot for your work @nuovecode and @mautz-et-tong

**Comment by nuovecode** [comment]
thank you so much!

**Comment by nuovecode** [comment]
@wigman may I ask you to add https://github.com/ilanarielbaron to credits?

**Comment by wigman** [comment]
@nuovecode Yes ofcourse, I missed that because it didn't show in the repo overview :) I've added it, but will wait with tagging another version until we get some feedback on this version.

**Pull request merged**
